spring:
  config:
    import: file:.env[.properties]
  datasource:
    url: ${DB_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.tradertopic.metsoft: DEBUG
    io.opentelemetry: INFO
    org.springframework.boot.actuate.autoconfigure.tracing: INFO
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}]"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
      otlp:
        enabled: true
        url: http://localhost:4318/v1/metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  opentelemetry:
    resource-attributes:
      service.name: otel-demo
      service.version: 0.0.1-SNAPSHOT
      deployment.environment: development

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs