spring:
  config:
    import: file:.env[.properties]
  datasource:
    url: ${DB_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.tradertopic.oteldemo: DEBUG
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId}]"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: otel-demo
    tracing:
      export:
        otlp:
          enabled: false
  otlp:
    metrics:
      export:
        enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs